sudo: enabled

dist: xenial

language: c

os:
- linux

compiler:
- gcc

before install:
- sudo apt-get -qq update

env:
  - ARCH_DIST='linux-amd64'

addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9

install:
- wget https://$ACCOUNT@update.cryptopro.ru/support/stunnel/mydsrf &&
  wget https://$ACCOUNT@update.cryptopro.ru/support/stunnel/dist/csp50/${ARCH_DIST}_deb.tgz &&
  tar -xvf ${ARCH_DIST}_deb.tgz;

script:
  - ./nginx-gost/install-nginx.sh --csp=${ARCH_DIST}_deb
  - ./prepare_silent_mod.sh
  - ./nginx-gost/install-certs.sh --silent
